/*
 * Pristine
 * SPDX-License-Identifier MIT
 */

#pragma once

#define KERNEL_BASE_ADDRESS   (0x200000)

#define KERNEL_STACK_SIZE     (0x4000)
#define KERNEL_STACK_START    (KERNEL_BASE_ADDRESS - 8)
#define KERNEL_STACK_END      (KERNEL_STACK_START - KERNEL_STACK_SIZE)

#define KERNEL_STACK_GUARD    (KERNEL_BASE_ADDRESS - KERNEL_STACK_SIZE - 4096)

#define KERNEL_TSS_RSP0_SIZE  (0x1000)
#define KERNEL_TSS_RSP0_START (KERNEL_STACK_GUARD - 8)
#define KERNEL_TSS_RSP0_END   (KERNEL_TSS_RSP0_START - KERNEL_TSS_RSP0_SIZE)

#define KERNEL_TSS_RSP0_GUARD (KERNEL_STACK_GUARD - KERNEL_TSS_RSP0_SIZE - 4096)

#define KERNEL_TSS_IST1_SIZE  (0x1000)
#define KERNEL_TSS_IST1_START (KERNEL_TSS_RSP0_GUARD - 8)
#define KERNEL_TSS_IST1_END   (KERNEL_TSS_IST1_START - KERNEL_TSS_IST1_SIZE)

#define KERNEL_TSS_IST1_GUARD (KERNEL_TSS_RSP0_GUARD - KERNEL_TSS_IST1_SIZE - 4096)